swagger: '2.0'
info:
  title: Breely API Gateway
  description: Proxies requests to the secure n8n webhook.
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
paths:
  /onboard:
    post:
      summary: Forwards client onboarding requests.
      operationId: forwardOnboardingRequest
      x-google-backend:
        address: https://breely-api-gateway-535002965287.us-central1.run.app # Replace with your breely-api-gateway URL
      responses:
        '200':
          description: A successful response
          schema:
            type: string
